version: "3.7"

services:
  api-gateway:
    image: adrianvsaint/minispace.apigateway:latest
    container_name: api-gateway
    restart: unless-stopped
    environment:
      - NTRADA_CONFIG=ntrada-async.docker.yml
    ports:
      - 5000:80
    networks:
      - minispace

  identity-service:
    image: adrianvsaint/minispace.services.identity:latest
    container_name: identity-service
    restart: unless-stopped
    ports:
      - 5004:80
    networks:
      - minispace

  students-service:
    image: adrianvsaint/minispace.services.students:latest
    container_name: students-service
    restart: unless-stopped
    ports:
      - 5007:80
    networks:
      - minispace

  events-service:
    image: adrianvsaint/minispace.services.events:latest
    container_name: events-service
    restart: unless-stopped
    ports:
      - 5008:80
    networks:
      - minispace
    
  web:
    image: adrianvsaint/minispace.web:latest
    container_name: web
    restart: unless-stopped
    ports:
      - 5606:80
    networks:
      - minispace

networks:
  minispace:
    name: minispace-network
    external: true