version: "3.7"

services:
  api-gateway:
    build: ../../MiniSpace.APIGateway
    container_name: api-gateway
    restart: unless-stopped
    environment:
      - NTRADA_CONFIG=ntrada.docker
    ports:
      - 5000:80
    networks:
      - minispace

  identity-service:
    build: ../../MiniSpace.Services.Identity
    container_name: identity-service
    restart: unless-stopped
    ports:
      - 5004:80
    networks:
      - minispace

networks:
  minispace:
    name: minispace-network
    external: true