# Konfiguration with ports
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['localhost:5000']

  - job_name: 'identity-service'
    static_configs:
      - targets: ['localhost:5004']

  - job_name: 'students-service'
    static_configs:
      - targets: ['localhost:5007']

  - job_name: 'events-service'
    static_configs:
      - targets: ['localhost:5008']

  - job_name: 'comments-service'
    static_configs:
      - targets: ['localhost:5009']

  - job_name: 'reactions-service'
    static_configs:
      - targets: ['localhost:5010']

  - job_name: 'friends-service'
    static_configs:
      - targets: ['localhost:5012']

  - job_name: 'posts-service'
    static_configs:
      - targets: ['localhost:5013']

  - job_name: 'mediafiles-service'
    static_configs:
      - targets: ['localhost:5014']

  - job_name: 'organizations-service'
    static_configs:
      - targets: ['localhost:5015']

  - job_name: 'notifications-service'
    static_configs:
      - targets: ['localhost:5006']

  - job_name: 'reports-service'
    static_configs:
      - targets: ['localhost:5005']

  - job_name: 'email-service'
    static_configs:
      - targets: ['localhost:5016']  

  - job_name: 'web'
    static_configs:
      - targets: ['localhost:5606']