name: .NET MiniSpace Microservice build & integration

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30  
    strategy:
      matrix:
        include:
          - project: 'MiniSpace.APIGateway/src/MiniSpace.APIGateway'
          - project: 'MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api'
            test_dir: 'MiniSpace.Services.Identity/tests'
          - project: 'MiniSpace.Web/src/MiniSpace.Web'
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 8.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies for ${{ matrix.project }}
        run: dotnet restore ${{ matrix.project }}

      - name: Build ${{ matrix.project }}
        run: dotnet build ${{ matrix.project }} --no-restore  

      - name: Setup .NET Core 3.1 for tests
        if: matrix.test_dir != ''
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies for test projects in ${{ matrix.test_dir }}
        if: matrix.test_dir != ''
        run: |
          echo "Restoring test projects in ${{ matrix.test_dir }}"
          find ${{ matrix.test_dir }} -name '*.csproj' -exec dotnet restore {} \;

      - name: Run tests in ${{ matrix.test_dir }}
        if: matrix.test_dir != ''
        run: |
          echo "Running tests in ${{ matrix.test_dir }}"
          set -e  # Ensure that the shell exits immediately if any command returns a non-zero status
          find ${{ matrix.test_dir }} -name '*.csproj' -exec sh -c 'dotnet test "{}" --no-restore --verbosity normal || exit 1' \;

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: SaintAngeLs/p_software_engineering_2
          fail_ci_if_error: true

