name: .NET MiniSpace Microservice build & integration

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30  
    strategy:
      matrix:
        include:
          - project: 'MiniSpace.APIGateway/src/MiniSpace.APIGateway'
          - project: 'MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api'
            test_dir: 'MiniSpace.Services.Identity/tests'
          - project: 'MiniSpace.Web/src/MiniSpace.Web'
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies for ${{ matrix.project }}
        run: dotnet restore ${{ matrix.project }}
      - name: Restore dependencies for test projects in ${{ matrix.test_dir }}
        if: matrix.test_dir != ''
        run: |
          echo "Restoring test projects in ${{ matrix.test_dir }}"
          find ${{ matrix.test_dir }} -name '*.csproj'
          find ${{ matrix.test_dir }} -name '*.csproj' -exec dotnet restore {} \;
      - name: Build ${{ matrix.project }}
        run: dotnet build ${{ matrix.project }} --no-restore
      - name: Run tests in ${{ matrix.test_dir }}
        if: matrix.test_dir != ''
        run: |
          echo "Running tests in ${{ matrix.test_dir }}"
          find ${{ matrix.test_dir }} -name '*.csproj' -exec echo "Testing {}" \;
          find ${{ matrix.test_dir }} -name '*.csproj' -exec dotnet test {} --no-build --verbosity normal \;
